[package]
edition = "2021"
name = "cavalier_contours_server"
version = "0.1.0"

[dependencies]
poem = {version = "1.0", features = ["static-files"]}
tokio = {version = "1.0", features = ["rt-multi-thread", "macros", "signal"]}
tracing-subscriber = {version = "0.3.9", features = ["env-filter"]}
